### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path

### ISSUE THREAD

**Issue by nikhilvks** [dblock/waffle#293] opened 2015-11-13 12:52 UTC
Hi,
 I have put up a sample java web application with Waffle for windows authentication. I am using Waffle 1.8 with Tomcat 8. I have it running and authenticating successfully in my dev environment (Windows 2012 R2 server). But when i run the same application in prod environment it gives below error when trying to access the url:

SEVERE [http-nio-443-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Jersey REST Service] in context with path [/Auth-Test] threw exception [Filter execution threw an exception] with root cause
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path ([file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/classes/, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/asm-3.1.jar, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/guava-18.0.jar, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/jersey-bundle-1.17.1.jar, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/jna-4.2.1.jar, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/jna-platform-4.2.1.jar, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/log4j-1.2.8.jar, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/slf4j-api-1.7.12.jar, file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/Auth-Test/WEB-INF/lib/waffle-jna-1.8.0.jar])
at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:866).....

The prod server is also Windows 2012 R2 server with the application deployed in tomcat8 and tomcat8 running as a service. 
My WEB-INF/lib/ contains asm-3.1.jar,guava-18.0.jar,jersey-bundle-1.17.1.jar, log4j-1.2.8.jar,slf4j-api-1.7.12.jar,waffle-jna-1.8.0.jar, jna-4.2.1.jar and jna-platform-4.2.1.jar

asm-3.1.jar, jersey-bundle-1.17.1.jar and log4j-1.2.8.jar are used for creating REST web service.

I tried moving jna-4.2.1.jar and jna-platform-4.2.1.jar to from WEB-INF/lib/ to tomcat8/lib. Still no success.

It would be a great help if a solution is provided or at least point me to a direction to troubleshoot the issue. Thanks in advance

**Comment by dblock** [comment] 2015-11-13 15:19
That DLL gets extracted by JNA, I believe into TEMP but I could be wrong, I wonder if there're permission problems?

**Comment by nikhilvks** [comment] 2015-11-17 10:30
I could not find jnidispatch.dll anywhere in my dev server.
I have noticed that in my dev server a folder named  'jna-686459134' is created under tomcat\temp with 2 files (jna3812812009318427361.dll and jna3812812009318427361.dll.x) inside this folder.
Whereas in prod server a folder named 'jna-2108433353' is created in temp folder, but this folder is EMPTY !!!.  So i suspect the JNA could not extract the dll files in this folder which causes the issue, but still could not find the root cause.
I have checked the tomcat if it enforces any permissions and verified that it is running without any security manager.
Would manually putting jnidispatch.dll in the resource path work? 
Please guide me if i am missing anything.

**Comment by dblock** [comment] 2015-11-17 11:32
It's pretty clearly the issue. Manually extracting anything is not going to work, JNA won't find it. Check file system permissions - who owns the folder? Is it writeable by everyone? Etc.

**Comment by nikhilvks** [comment] 2015-11-18 07:37
I have resolved the issue.
The root cause for the issue was the jna jar file got corrupted while transferring the war file to prod server. I replaced  the jna jar file in prod server with a fresh copy of jar file it got working. 
Thanks for the support. Waffle rocks.

**Comment by nikhilvks** [comment] 2015-11-18 07:39
I would like to know how waffle works for Kerberos authentication. Just a high level work flow is sufficient. If there is any technical documentation available, please point me.

**Comment by dblock** [comment] 2015-11-18 12:05
http://www.slideshare.net/dblockdotorg/waffle-at-nycjavasig could be a good place to start for high level flow, there's a diagram for how SSPI works, waffle is just a wrapper on top. There're some good blog posts like [this one](http://tuhrig.de/a-windows-sso-for-java-on-client-and-server/).

I think we would welcome a PR that adds either an FAQ or a top-level section that describes how "it all works".

**Comment by dblock** [comment] 2015-11-18 12:06
It's crazy that the root cause was a corrupted jna.jar! How did you ever find this?! 

Closing the issue.

**Closed by dblock** 2015-11-18 12:06 UTC
Labels: bug?

**Comment by nikhilvks** [comment] 2015-11-19 07:38
All i could say is it was a hunch. I could not find anything that could go possibly wrong and then somehow this thought came to my mind "what if jar is not proper?". Then to verify i ran java -jar jna-4.2.1.jar command on my dev machine and it gave output as: 
Java Native Access (JNA) API Version 4
Version: 4.2.1 (b0)
 Native: 4.0.1 (1a6047467b59e8748f975e03016ce3d9)
 Prefix: win32-x86

Then i ran the same command on the prod server and it gave me the exception:
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path

**Comment by nikhilvks** [comment] 2015-11-19 07:39
Thanks for sharing the links.

**Comment by dblock** [comment] 2015-11-19 12:15
@nikhilvks Can you add this to the FAQ please?
